exclude = [
  "localhost",
  "127\\.0\\.0\\.1",
  "file://",
  "example\\.com",
  "github\\.com/.*/compare/.*v.*\\.\\.\\..*v",
  "github\\.com/.*/releases/tag/.*v\\d",
  "github\\.com/.*/security/advisories/new",
  "github\\.com/blineai/bline",
  "app\\.fossa\\.com/api/projects/.*\\.svg",
]

exclude_path = ["CHANGELOG.md"]

max_retries = 5
retry_wait_time = 3
