name: Link Check

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/link-check.yml"
  pull_request:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/link-check.yml"
  merge_group: {}
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

concurrency:
  group: link-check-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  check:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --no-progress --config lychee.toml '**/*.md'
          fail: ${{ github.event_name != 'pull_request' }}
